### ISSUE TITLE
Sort the list of games on the server. 

### ISSUE THREAD

**Issue by LETRA** [tgass/macbeth#18]
It would be interesting press the column header to sort the list of games for rating or mode (standard, blitz, etc).

Thank you !! :-)

**Comment by tgass** [comment]
This is done. With the next release you will find all the sort attributes in a sub-menu. Seems more orderly to me ;)

**Comment by LETRA** [comment]
Splendid. Do you think include Macbeth in the Mac App Store? That would be a good idea :-)
