### ISSUE TITLE
Parameters in config file

### ISSUE THREAD

**Issue by LETRA** [tgass/macbeth#3]
Hello. First, thank you for your work in the app. My question is about the parameters of config file. How configure? Thank you.

**Comment by tgass** [comment]
Hi LETRA, 
thank you so much for your interest in Macbeth. I hope that I can answer your question. There are two ways to change the configuration:
1. change configuration file directly:
   the configuration file lies at /Applications/Macbeth.app/Contents/Resources/macbeth.yaml given that you put Macbeth in your /Applications folder. Just open the file with a text editor.
2. via Macbeth:
   start Macbeth and the go to "File" -> "Settings" in the top navigation bar/ top of your screen.

There are currently only very few parameters to change:

logging:
stdOut: prints log messages to standard out, but only if the binary is executed directly (a feature that is maybe only important to me during development). Values: [true|false]
file: writes log messages to a file in Macbeth home directory. Values: [true|false]

directory: this is the directory where your games will be stored (and if activated log messages as well)

If you like, write me an email to tilmann@macbeth-ficsclient.com. I'm very much interessted in my users' opinions about Macbeth.

**Comment by LETRA** [comment]
Hello. Thank you for responding so quickly. First, a question: Does the parameter "login" may contain the password? What is the syntax? (I think this should be documented).

Regarding the program I think is very functional but missing some details. In my case I have used a Macbook Pro with Mavericks on, and then will try it on my desktop computer with El Capitan.

It’s this detail that does not save the user name and password, at least in my case. We also need sound board. The program design is good enough (colors of the board, pieces). And, for example, need some quick command buttons to enter "say hello", "say good game" with the style of eboard in Linux.

Ultimately I think Macbeth lacks little to be fully functional. With some solutions should be part of the interfaces page of FICS where there is a notable lack of them for OSX. I think that would be much more popular the app. It has been very difficult to find. I think if known more many users prefer Macbeth better than interfaces with Java. And even it would be very interesting to see it on the Mac App Store.

Thanks for your work & Greetings from Spain.

Jose Ramon

**Comment by tgass** [comment]
Hi Jose,
thank you so much for the input. I created an issue for all your suggestions! Please feel free to add issues for all the features you would like to have. It's really good to get some feedback and see Macbeth used in the wild!

About storing username/password. Is the following describtion adequate?

If you login, there should be a checkbox "Save credentials".
If checked, Macbeth stores username and password and logs you in automatically from then on.
There should be a config property "auto-login", so you can disable automatic login (and change user)

Grüße aus Berlin
Tilmann

**Comment by LETRA** [comment]
Hi Tilmann. Thank you very much for supporting my suggestions. The description is correct. I have no programming skills but if I can be of help in something will be happy to do so. You can let me know when a beta version and I will be happy to give feedback with all my impressions. Two new ideas would be a size larger font for the console and a tab to see your own rating and history of recent games. I think Macbeth might be the best app for FICS in OSX. I think you've done most of the good work and just missing some details.

All the best,

Jose Ramon

**Comment by tgass** [comment]
Hi Jose,

I just uploaded a new version. You can now configure and use Auto-Login and variable console font-size. Please have a look!

**Comment by LETRA** [comment]
Works great! Thank you Tilman!

**Comment by tgass** [comment]
Hi Jose,
I just released a new version, just now. Did you get some kind of notification? I'd like to post more stuff in the future via release sor issues. If you don't mind, please subscribe to all issues.
I hope you like the improvements!

**Comment by LETRA** [comment]
Hi Tilmann. Thanks for the warning. I have received other mails. I will go through the development of Macbeth. I am happy that you admit suggestions and I, as a Mac user, I thank you enormously all the work you're doing.

I by testing sounds first. I think there is a problem with timing. And I think there may be another problem. It has happened something strange. I opened several games to watch and all were completed. If a match was occurring. But the sounds were out of synch with the movements. I do not know the reason that the match had finished to watch. It never happened to me to watch games from Macbeth. It can also be a fluke.

Then I keep trying the other features.

Thank you!!

Jose Ramon

**Comment by tgass** [comment]
Thank you so much for the feedback! Is the sound always out of sync or only if you observe several games? I'll see if I get fix this quickly!

**Comment by LETRA** [comment]
Hi Tilmann! It's curious. The bug occurs in my MBP 2007 (SR) with El Capitan supported (6GB RAM, 256GB SSD). But in my Mac Mini 2012 (16GB RAM, not SSD) with El Capitan too, Macbeth working properly. Perhaps it is a problem of system resources. You can try it with an old mac?

**Comment by tgass** [comment]
Hi Jose,
thanks again so much for your feedback. After reading your message I decided to use a completely different mechanism to create sounds. It was more challenging than expected! 
If you like you can download a pre-release via dropbox. I'm very much interested if the problems you describe are still occuring. I seriously hope not!
https://www.dropbox.com/s/buse9bfv3lveu5a/Macbeth.dmg?dl=0

I found out that some of the .wav file are recorded with different sampling rates and are somehow played distorted: woodthunk.wav, slap.wav, thud.wav. Please change them in the configuration to null or move.wav !

Looking forward again to your message!
Tilmann

**Comment by LETRA** [comment]
Hello Tilmann,

(My test in MacMini 2012). At first I heard no sound. In a game later just some of the sounds were heard. I changed the settings move/normal to move.wav. From that moment, in the first game they were first heard some moves and then I can see the movement on the board. In the next two games I've observed the sounds were synchronized with the movements. Is rare. And I suppose that programming isn’t an exact science at first of the app.

A greeting,

Jose Ramon

**Comment by tgass** [comment]
Hi Jose,
I just uploaded a new version to the website. If you use it, please go to File -> Settings and update the sound configuration.
In case the sounds still don't work correctly, please let me know! Especially, OSX-version and RAM are of interest.
Thank you!

**Comment by LETRA** [comment]
Hi Tilmann. I have tested in MacMini 2012 with 16GB RAM and OSX 10.11.5. I think it works correctly. The sounds were not working completely good on this machine before. However now there have been no failures. I have even observed two games simultaneously and sounds could be heard well on the two boards :-)

**Comment by tgass** [comment]
Hi Jose. That's really good news! I'm so releaved that everythings seems to work fine! I'm already working on a simple in-game chat. Cheers!

**Comment by tgass** [comment]
Hi Jose!
After months and months of no update I finally uploaded a new version. I started a new job and tried to enjoy the summer as much as possible, so I took a small break from developing Macbeth. But now the new release is out. Please have a look!

I added basic chatting functionality, but I want to warn you a little bit. I didn't use the feature much myself, so maybe you run into usecases where the functionality doesn't match what you need or expect. So please let me know how I can improve. It is still very basic at the moment.

And I added the ability to sort PlayersList / GamesList over different columns. Unfortunately not by clicking on the table head (that was technically somehow not possible, but might be in the future). Instead if you right-click on the table, you will find separate menu items for sorting.)

That's it for now, please let me know what you would like to see next in Macbeth! Maybe the Fics 'notify' feature?

I hope you also enjoy the summer!

Best,
Tilmann

**Comment by LETRA** [comment]
Wonderfull Tilmann! Tonight over it and tell you. I do not know what new feature could propose. I too like a quick and simple app, yet powerful. I think I'll do a thorough review to see what happens to me. Too much you enjoy your summer and your new job. 

All the best!!

Jose Ramon

**Comment by LETRA** [comment]
Hi Tilmann. From what I'm seeing Macbeth works very well. If I have to propose a feature that would be to have a button to watch the best FICS live games. I miss also see the ratings of the players next to their name. And maybe some boards of other well graduated colors. No textures, but well combined colors. I do not want to think more ideas in your holidays !!

Thank you very much for your work. And greetings from Madrid.

Jose Ramon
